### ISSUE TITLE
Better Documentation?

### ISSUE THREAD

**Issue by C41Underscore** [yoursunny/esp32cam#13]
This looks like a really cool library but it completely lacks function documentation, which would be really helpful, as opposed to using examples to work out how to use it.

**Comment by yoursunny** [comment]
More functions have Doxygen. If you edit code in Visual Studio Code, you'll see documentation as you type.

**Comment by yoursunny** [comment]
Doxygen is now being built in CI and published to https://esp32cam.yoursunny.cn/
