### ISSUE TITLE
Set the image quality

### ISSUE THREAD

**Issue by UKNickyD** [yoursunny/esp32cam#14]
How do we set the image quality? I can see in the examples how to set resolution, but no way to set quality.

Thanks

**Comment by yoursunny** [comment]
If you are referring to JPEG quality, use `config.setJpeg(70)`:
https://github.com/yoursunny/esp32cam/blob/fc136a4d5a4a41ad8d2eac4545964fc0a731c78c/src/internal/config.hpp#L47-L50

**Comment by UKNickyD** [comment]
Excellent! 

Thanks for the quick reply, and well done on an great library :)
