### ISSUE TITLE
WifiCam example: "Not found: /"

### ISSUE THREAD

**Issue by DocTu06** [yoursunny/esp32cam#21]
When uploading the wificam example code to the esp32 cam, when I try to go to the ip adress,there is just an empty page with the text "Not found: /"

**Comment by DocTu06** [comment]
I did not change the code in any way, just changed the ssid and password to match my network

**Comment by yoursunny** [comment]
This is expected behavior because there's no handler registered for `/` URI.
The serial console will tell you which URIs are available.

**Comment by yoursunny** [comment]
e481b4cc9aeb8ed3da460644dc7d7d1a51b0fdb2 adds a handler for `/` URI, which links to various picture formats and resolutions.
Nevertheless, not every resolution would work on a particular camera.
