### ISSUE TITLE
i cant compile

### ISSUE THREAD

**Issue by althaf404** [yoursunny/esp32cam#38]
c:\Users\user\Documents\Arduino\libraries\esp32cam-main\src\esp32cam.cpp: In member function 'esp32cam::ResolutionList esp32cam::CameraClass::listResolutions() const':
c:\Users\user\Documents\Arduino\libraries\esp32cam-main\src\esp32cam.cpp:30:3: error: 'camera_sensor_info_t' was not declared in this scope
   camera_sensor_info_t* info = esp_camera_sensor_get_info(&sensor->id);
   ^
c:\Users\user\Documents\Arduino\libraries\esp32cam-main\src\esp32cam.cpp:30:25: error: 'info' was not declared in this scope
   camera_sensor_info_t* info = esp_camera_sensor_get_info(&sensor->id);
                         ^
c:\Users\user\Documents\Arduino\libraries\esp32cam-main\src\esp32cam.cpp:30:70: error: 'esp_camera_sensor_get_info' was not declared in this scope
   camera_sensor_info_t* info = esp_camera_sensor_get_info(&sensor->id);
                                                                      ^
Multiple libraries were found for "esp32cam.h"
  Used: C:\Users\user\Documents\Arduino\libraries\esp32cam-main
  Not used: C:\Users\user\Documents\Arduino\libraries\EloquentEsp32cam
exit status 1

Compilation error: exit status 1

**Comment by yoursunny** [comment]
https://github.com/yoursunny/esp32cam/issues/36#issuecomment-1193252152
