### ISSUE TITLE
how to solve

### ISSUE THREAD

**Issue by Nithyasri-12** [yoursunny/esp32cam#44]
Error resolving FQBN: getting build properties for board esp32:esp32:esp32wrover: invalid option 'EraseFlash'

Compilation error: Error resolving FQBN: getting build properties for board esp32:esp32:esp32wrover: invalid option 'EraseFlash'

**Comment by yoursunny** [comment]
> invalid option 'EraseFlash'

This is either a hardware issue or Arduino core installation problem.
Does "blink" example work on your device?
