### ISSUE TITLE
CAM stream and SPIFFS html page

### ISSUE THREAD

**Issue by array81** [yoursunny/esp32cam#5]
I'd like upload a HTML webpage on SPIFFS then call it from client and show cam video or image on inside a webpage section (for example a DIV). In this moment I think this is not possible with your library.
Is it possible add it?

**Comment by yoursunny** [comment]
It is possible, but it's out of scope of this library.
Since most HTTP implementations on the ESP32 can only work with one socket at a time, you probably want to place HTML assets and the camera stream on two separate HTTP servers listening on different ports.
