### ISSUE TITLE
Error when trying Wifi Cam

### ISSUE THREAD

**Issue by AliNavaid** [yoursunny/esp32cam#52]
C:\Users\coolz\AppData\Local\Temp\.arduinoIDE-unsaved2024025-14784-1vft4t4.chfw\WifiCam\handlers.cpp:3:27: fatal error: uri/UriBraces.h: No such file or directory
compilation terminated.

exit status 1

Compilation error: uri/UriBraces.h: No such file or directory

**Comment by yoursunny** [comment]
`uri/UriBraces.h` shall refer to the header in WebServer library, which is part of Arduino core for ESP32.
https://github.com/espressif/arduino-esp32/blob/2.0.14/libraries/WebServer/src/uri/UriBraces.h
Have you selected the correct board model?

**Comment by farmeresmarthome** [comment]
In file included from C:\Users\phero\AppData\Local\Temp\.arduinoIDE-unsaved2025426-9212-w5f0bs.3m10h\WifiCam\WifiCam.ino:1:
C:\Users\phero\AppData\Local\Temp\.arduinoIDE-unsaved2025426-9212-w5f0bs.3m10h\WifiCam\WifiCam.hpp:4:10: fatal error: esp32cam.h: No such file or directory
    4 | #include <esp32cam.h>
      |          ^~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: esp32cam.h: No such file or directory

ERROR WITH IDE 2.3.6. I SUPPORT .THANK

**Comment by farmeresmarthome** [comment]
Can you improve the library to fit the current ide?.thank

**Comment by yoursunny** [comment]
> fatal error: esp32cam.h: No such file or directory

I tested with Arduino IDE 2.3.6 and arduino-esp32 3.2.0, but cannot reproduce this error.
Most likely you did not clone esp32cam repository to the right place.
For Windows, it should be in `C:\Users\username\Documents\Arduino\libraries\esp32cam`.
