### ISSUE TITLE
Memory with higher resolutions. 

### ISSUE THREAD

**Issue by alorbach** [yoursunny/esp32cam#7]
Sorry to bother again, I am expiriencing memory issues with higher resolutions as I have lots of other code running besides this. 

Do you think there it could be possible to use PSRAM to store the frames? 
I am using configuration like: 
```
  cfg.setResolution(Resolution::find(640, 480));
  cfg.setJpeg(85);
  cfg.setBufferCount(2);
```

Which blocks working memory buffer for 2 images, in my case the remaining free memory is just ~ 30-40kb which is ok but if it drops below 30kb, it becomes unstable.

**Comment by yoursunny** [comment]
As mentioned in [README](https://github.com/yoursunny/esp32cam/blob/9c4eb5dad6d383a3a6a28dc358aa7a6602de2b92/README.md):

> In ESP32 Arduino, the board type should be set to "ESP32 WROVER" to enable 4MB external PSRAM. Otherwise, internal RAM is insufficient to support high resolution.

This configuration has been tested on AI Thinker ESP32-CAM with 800x600 resolution.
